// Generated by CoffeeScript 1.7.1
(function() {
  var NICE_INTERVALS, buckets;

  NICE_INTERVALS = [1, 1.2, 1.5, 1.6, 2, 2.5, 3, 5, 8];

  buckets = function(stops, range) {
    var bucket, highest, interval, lowest, magnitude, max, min, n, smallest, _i, _len;
    lowest = range[0], highest = range[1];
    smallest = (highest - lowest) / stops;
    magnitude = Math.pow(10, Math.floor((Math.log(smallest)) / Math.log(10)));
    for (_i = 0, _len = NICE_INTERVALS.length; _i < _len; _i++) {
      interval = NICE_INTERVALS[_i];
      bucket = interval * magnitude;
      if (bucket < smallest) {
        continue;
      }
      min = bucket * (Math.floor(lowest / bucket));
      max = min + (bucket * stops);
      if (max >= highest) {
        break;
      }
    }
    return (function() {
      var _j, _ref, _results;
      _results = [];
      for (n = _j = 0, _ref = stops - 1; 0 <= _ref ? _j <= _ref : _j >= _ref; n = 0 <= _ref ? ++_j : --_j) {
        _results.push((function(m) {
          return [m, m + bucket];
        })(min + n * bucket));
      }
      return _results;
    })();
  };

  if (!((typeof module !== "undefined" && module !== null) || (typeof requirejs !== "undefined" && requirejs !== null))) {
    this.buckets = buckets;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = buckets;
  }

  if ((typeof requirejs !== "undefined" && requirejs !== null) && (typeof define !== "undefined" && define !== null)) {
    define(buckets);
  }

}).call(this);
